"""approval_log_nullable_columns

Revision ID: 399727c64ab8
Revises: e1082c2cfd13
Create Date: 2026-06-08 00:25:07.069168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '399727c64ab8'
down_revision: Union[str, Sequence[str], None] = 'e1082c2cfd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_log', 'approver_employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('approval_log', 'approval_result',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('approval_log', 'approval_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_log', 'approval_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('approval_log', 'approval_result',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('approval_log', 'approver_employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
